import { StudyOutput } from "./types";

export function generateMarkdown(output: StudyOutput): string {
  const lines: string[] = [];
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  lines.push(`# ${output.title}`);
  lines.push(`*Generated by Kindling · ${date}*`);
  lines.push("");
  
  if (output.format === "flashcards" && output.flashcards) {
    lines.push("## Flashcards");
    lines.push("");
    output.flashcards.forEach((card, i) => {
      lines.push(`### Card ${i + 1}`);
      lines.push(`**Q:** ${card.front}`);
      lines.push("");
      lines.push(`**A:** ${card.back}`);
      lines.push("");
      lines.push("---");
      lines.push("");
    });
  }

  if (output.format === "summary" && output.summary) {
    lines.push("## Summary");
    lines.push("");
    output.summary.forEach((chunk) => {
      lines.push(`### ${chunk.heading}`);
      lines.push(chunk.body);
      lines.push("");
    });
  }

  if (output.format === "qa" && output.qa) {
    lines.push("## Q&A");
    lines.push("");
    output.qa.forEach((item, i) => {
      lines.push(`**${i + 1}. ${item.question}**`);
      lines.push("");
      lines.push(`> ${item.answer}`);
      lines.push("");
    });
  }

  if (output.format === "flowdiagram" && output.mermaidCode) {
    lines.push("## Flow Diagram");
    lines.push("");
    lines.push("```mermaid");
    lines.push(output.mermaidCode);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("*Made with [Kindling](https://kindling.app) — Ignite the way you learn.*");

  return lines.join("\n");
}

export function downloadMarkdown(output: StudyOutput): void {
  const md = generateMarkdown(output);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${output.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_kindling.md`;
  a.click();
  URL.revokeObjectURL(url);
}
